import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import {useUser} from '../lib/hooks'
import Navbar from '../src/layouts/Navbar'
import styles from '../styles/Home.module.css'
import { ProjectCard } from '../src/components/cards';
import { fetchProjects } from '../src/util/apiFunctions';


export default function Home() {
  const user = useUser()
  const [projects, setProjects] = useState([]);

  useEffect(async () => {
    setProjects(await fetchProjects());
  }, [])

  console.log(JSON.stringify(user, null, 2))

  return (
    <div>
      <Head>
        <title>Hendricks Project Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        {projects?.map((project, index) => (
          
            <ProjectCard 
              key={project.id} 
              title={project.name}
              {...project}
            />
  
        ))}        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
