import React, { useState, useEffect } from 'react';
import Head from 'next/head'
// import useUser from '../lib/useUser'
import Navbar from '../components/Navbar'
// import styles from '../styles/Home.module.css'
import { CreateProjectButton, ProjectCard } from '../components/cards';
import axios from 'axios';
import CreateProjectModal from '../components/modals/CreateProjectModal';
import { ProjectContainer } from '../components/containers';


export default function Home() {
  const [projects, setProjects] = useState([]);
  const [displayModal, setDisplayModal] = useState('')
  // const user = useUser()

  useEffect(async () => {
    async function fetchProjects() {
      try {
        const res = await axios.get('/api/projects');
        console.log(res.data.data)
        setProjects(res.data.data)
      } catch (error) {console.log(error)}
    }
    fetchProjects()
  }, [])


  return (
    <div>
      <Head>
        <title>Hendricks Project Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <ProjectContainer>

        <CreateProjectButton onClick={() => setDisplayModal('createProject')} />
        {projects?.map((project, index) => (
          <ProjectCard 
          key={project._id} 
          title={project.name}
          {...project}
          />
          ))}   
        </ProjectContainer>

      {displayModal && (
        <>
          {displayModal === 'createProject' && (
            <>
              <CreateProjectModal
                closeModal={() => setDisplayModal('')}
                onProjectCreated={(newProject) => {
                  setProjects([...projects, newProject]);
                  setDisplayModal('');
                }}
              />
            </>
          )}
        </>
      )}
    </div>
  )
}
